// AUTO-GENERATED by packages/ui/scripts/extract-changelog.mjs; do not edit by hand.
// Regenerate with: pnpm --filter @eagami/ui docs:changelog

export interface ChangelogSection {
  heading: string;
  entries: string[];
}

export interface ChangelogRelease {
  version: string;
  date: string;
  sections: ChangelogSection[];
}

export const UI_CHANGELOG: readonly ChangelogRelease[] = [
  {
    version: '5.39.0',
    date: '2026-09-08',
    sections: [
      {
        heading: 'Added',
        entries: ['Add image-plus, image-search, microscope, and rows icons.'],
      },
    ],
  },
  {
    version: '5.38.1',
    date: '2026-09-01',
    sections: [
      {
        heading: 'Changed',
        entries: [
          'Tidy the internal docs metadata and test coverage behind the field label icon, with no change to the published API.',
        ],
      },
    ],
  },
  {
    version: '5.38.0',
    date: '2026-08-30',
    sections: [
      {
        heading: 'Added',
        entries: [
          'Add a `labelIcon` input to every labelled field component, from the inputs and pickers to the sliders, radio group, rating, segmented control, file uploader and form field, rendering an icon component before the label text through the shared field label.',
        ],
      },
    ],
  },
  {
    version: '5.37.0',
    date: '2026-08-30',
    sections: [
      {
        heading: 'Added',
        entries: [
          'Add a `modal` input to the dialog: when true (the default) the page behind is inert and cannot scroll, while false opens it non-modally via `show()`, floating with no backdrop, so the page behind stays scrollable and interactive.',
          'Expand the icon set with two image-editing icons: contrast and rotate ccw square.',
        ],
      },
    ],
  },
  {
    version: '5.36.0',
    date: '2026-08-25',
    sections: [
      {
        heading: 'Changed',
        entries: [
          "Allow typing a time straight into the time picker's field: hand-typed text is read leniently on Enter or blur, in 12- or 24-hour notation with or without separators, unreadable text falls back to the held value, and cleared text clears it.",
        ],
      },
    ],
  },
  {
    version: '5.35.0',
    date: '2026-08-22',
    sections: [
      {
        heading: 'Added',
        entries: [
          'Add `uppercase` to the button, tag and badge, rendering their text in all capitals.',
          'Add an `--ea-button-radius` hook, so a button can become a pill through its own chrome.',
        ],
      },
      {
        heading: 'Fixed',
        entries: [
          "Keep the dialog body's scrollbar gutter reserved, so content sitting at the overflow threshold no longer flickers between its scrollbar states.",
        ],
      },
    ],
  },
  {
    version: '5.34.0',
    date: '2026-08-20',
    sections: [
      {
        heading: 'Added',
        entries: [
          'Add `popoverMaxHeight` to the multi-select, capping how tall the option popover may grow before its list scrolls.',
          "Add an `--ea-file-uploader-dropzone-padding` hook, so a consumer can tighten the dropzone through the uploader's own chrome.",
        ],
      },
      {
        heading: 'Fixed',
        entries: [
          'Apply `--ea-button-padding` to icon-only buttons too, which kept their built-in square padding and ignored the hook.',
        ],
      },
    ],
  },
  {
    version: '5.33.0',
    date: '2026-08-18',
    sections: [
      {
        heading: 'Added',
        entries: [
          "Add `--ea-button-padding` and `--ea-button-min-height` hooks, so a consumer can tighten an icon button to its glyph through the button's own chrome rather than by reaching into it.",
        ],
      },
      {
        heading: 'Fixed',
        entries: [
          "Keep the swatch's colour covering its transparency checkerboard exactly: both now paint on the one box, so sub-pixel rounding at fractional sizes can no longer leave a rim of the pattern flickering at the edge.",
        ],
      },
    ],
  },
  {
    version: '5.32.0',
    date: '2026-08-18',
    sections: [
      {
        heading: 'Added',
        entries: [
          'Add `snapValues` to the slider: values the thumb is pulled onto while dragging, each drawn as a tick on the track, so a marked value can be landed exactly.',
        ],
      },
      {
        heading: 'Fixed',
        entries: [
          'Stop a slider from following the cursor after the button is released: a drag now starts only on the primary button, ends the moment a move arrives with no button held, and captures the pointer on the track itself.',
        ],
      },
    ],
  },
  {
    version: '5.31.0',
    date: '2026-08-18',
    sections: [
      {
        heading: 'Changed',
        entries: [
          'Match every text filter past accents, so a term typed on a plain keyboard finds the accented spelling ("jablko" finds "Jabłko"): the multi-select\'s search and its create-row duplicate check, the autocomplete\'s option filtering, the dropdown\'s typeahead, and the command palette\'s filter.',
        ],
      },
      {
        heading: 'Fixed',
        entries: [
          'Keep focus rings and slider thumbs from being cut off at the bottom of a scrolling dialog body: the seam under the body now lives inside its scroll box instead of on the slot beneath it.',
          "Centre a field's error icon on the eye's line with the message text, where it sat a pixel low.",
        ],
      },
    ],
  },
  {
    version: '5.30.2',
    date: '2026-08-16',
    sections: [
      {
        heading: 'Fixed',
        entries: [
          'Fix every popover opened from inside a modal dialog being unusable: its surface now sits inside the dialog, where a select, autocomplete, date picker or menu can take the focus and the pointer again.',
          "Balance a dialog's padding across every combination of slots: each seam between two slots carries a single gap, no seam is padded from both sides, and the outermost slot on each side carries the panel's own edge.",
        ],
      },
    ],
  },
  {
    version: '5.30.1',
    date: '2026-08-16',
    sections: [
      {
        heading: 'Fixed',
        entries: [
          'Fix a popover opened from inside a modal dialog being left in the normal layer, where it took no focus and closed on its own clicks.',
        ],
      },
    ],
  },
  {
    version: '5.30.0',
    date: '2026-08-16',
    sections: [
      {
        heading: 'Added',
        entries: [
          'Add `--ea-dialog-inset`, `--ea-dialog-radius`, `--ea-dialog-max-height`, `--ea-dialog-header-padding`, `--ea-dialog-body-padding` and `--ea-dialog-status-padding`, so a dialog can run edge to edge or tune its chrome per instance.',
          'Ship an `@eagami/ui/testing` entry point with a native dialog shim for jsdom test runs.',
        ],
      },
      {
        heading: 'Changed',
        entries: [
          "**Breaking:** Move the dialog's close button into the header row, so header content lays out against it instead of reserving room by hand.",
          "**Breaking:** Restore the tag's uncapped default width, making `maxWidth` clipping opt-in again.",
        ],
      },
      {
        heading: 'Fixed',
        entries: ['Fix tooltips collapsing to a sliver of their text in Safari.'],
      },
    ],
  },
  {
    version: '5.29.0',
    date: '2026-08-16',
    sections: [
      {
        heading: 'Added',
        entries: [
          'Let a dialog refuse a close: `manualClose` reports every close route through `closeRequested` and leaves the dialog open until the consumer closes it.',
          'Add `closeDisabled` to the dialog, for a close button that has to be unavailable while a task is in flight.',
          "Add a `status` slot to the dialog, held between the body and the footer and out of the body's scroll box.",
          'Extend the dialog and drawer width scale with a `2xl` step above `xl`.',
          'Offer a Create row in the multi-select through `allowCreate`, reporting the typed text as `created` when the search matches no option.',
          'Give the tag a `color` input that paints the chip from a hex value and picks whichever ink reads on it.',
          'Accept a fluid `maxWidth` on the tag, so a chip can be capped against its container rather than a fixed width.',
          'Add `truncate` to the checkbox, ellipsizing a label too long for its column and revealing the full text in a tooltip.',
          'Add a `compact` colour picker trigger, a bare swatch without the value text or the clear button.',
          'Let a tooltip move to the side that fits with `flip`, and show only over clipped content with `whenClipped`.',
          "Expose the dialog header typography, the input focus treatment, and the code input's cells, spacing and state borders as custom properties.",
        ],
      },
      {
        heading: 'Changed',
        entries: [
          '**Breaking:** Move a tooltip with no room on its requested side to the opposite one by default; set `flip` to false for the old behaviour of nudging it inward.',
          'Toggle a focused checkbox on Enter, which a native checkbox leaves to the form.',
          'Hold a dialog inside the viewport, so a wide preset no longer overflows a narrow screen sideways.',
          "Balance a dialog's body padding when it has no header or no footer, instead of leaving the content tight against one edge.",
        ],
      },
    ],
  },
  {
    version: '5.28.0',
    date: '2026-08-16',
    sections: [
      {
        heading: 'Added',
        entries: [
          "Accept an image dropped onto the avatar editor's preview, outlined and captioned while a file is held over it.",
        ],
      },
      {
        heading: 'Changed',
        entries: [
          'Keep an open dropdown on the side of its field it opened on, moving it only when that side no longer fits.',
          "Move focus to the multi-select's last remaining match as it is typed, so Enter takes it and clears the search for the next one.",
          "Give the multi-select's search input focus as soon as its panel opens.",
          "Reword the avatar editor's drop prompt away from uploading, and settle on the camera icon for both of its prompts.",
        ],
      },
      {
        heading: 'Fixed',
        entries: [
          'Redraw the avatar editor when a dropped image replaces the one already loaded.',
          'Keep a dialog, drawer, command palette or popover open when a drag that began inside it is released outside, so selecting text no longer dismisses it.',
          'Fix the dead space left beside a tooltip that wraps after a page zoom.',
          'Hold the multi-select at one height once its chips start to scroll.',
        ],
      },
    ],
  },
  {
    version: '5.27.0',
    date: '2026-08-14',
    sections: [
      {
        heading: 'Added',
        entries: [
          'Add a `spellcheck` input to the input, left to the browser default when unset.',
        ],
      },
      {
        heading: 'Fixed',
        entries: [
          "Stop the command palette's search field from spellchecking the commands typed into it.",
        ],
      },
    ],
  },
  {
    version: '5.26.1',
    date: '2026-08-14',
    sections: [
      {
        heading: 'Fixed',
        entries: [
          "Clear the command palette's search when Enter is pressed on its clear button, which ran the highlighted command instead.",
          "Narrow the input's `aria-activedescendant` to a single unset form, so it no longer accepts both `null` and `undefined`.",
          "Run a command palette's `disabledWhen` predicate once per matching command rather than on every keystroke and hover.",
        ],
      },
    ],
  },
  {
    version: '5.26.0',
    date: '2026-08-14',
    sections: [
      {
        heading: 'Added',
        entries: [
          'Add `disabledWhen` to the command palette, a predicate that disables matching commands, and keep disabled commands visible as greyed-out, inert rows instead of hiding them.',
          'Add `keepIcon` to the input, keeping the leading icon while the field has a value, with `false` restoring the previous hide-with-placeholder behaviour.',
          'Forward `role`, `aria-expanded`, `aria-controls`, `aria-activedescendant`, and `aria-autocomplete` from the input to its native control for combobox-style hosts.',
        ],
      },
      {
        heading: 'Changed',
        entries: [
          '**Breaking:** Remove the unused `commandPalette.clear` message from the localized message set.',
          "Rebuild the command palette's search field on the input component, giving it the standard focus ring, leading search icon, and clear button.",
          'Soften dividers to a translucent wash in both themes across the command palette, grouped option lists, and the divider.',
          "Inset the command palette's top divider to match its section rules.",
          "Shrink the input's leading icon to two thirds of its previous size.",
        ],
      },
    ],
  },
  {
    version: '5.25.1',
    date: '2026-08-13',
    sections: [
      {
        heading: 'Fixed',
        entries: [
          'Scale the remaining fixed gaps and paddings with the `size` input across the stepper, radio, radio group, tabs, multi-select, transfer list, slider, range slider, code input, autocomplete, dropdown, data table, badge, file uploader, and segmented control.',
          'Apply the `2xs` size to the tabs, which previously fell back to the surrounding font size.',
          "Scale the stepper's optional-step caption with the `size` input.",
        ],
      },
    ],
  },
  {
    version: '5.25.0',
    date: '2026-08-12',
    sections: [
      {
        heading: 'Added',
        entries: [
          'Add `dismissDelay` to the tooltip, a grace period before a scrollable bubble hides so the pointer can reach it.',
        ],
      },
      {
        heading: 'Changed',
        entries: [
          'Keep every tooltip inside the viewport, scrolling content that no longer fits and letting the pointer reach it, with `--ea-tooltip-viewport-margin` setting the gap left at each edge.',
        ],
      },
    ],
  },
  {
    version: '5.24.0',
    date: '2026-08-11',
    sections: [
      {
        heading: 'Added',
        entries: [
          "Accept a toast's title and message as text segments, drawing the parts marked strong at full strength while the rest of the line steps back, with `--ea-toast-strong-weight` to retune the weight.",
        ],
      },
      {
        heading: 'Changed',
        entries: ['Draw the spinner in the primary brand colour.'],
      },
    ],
  },
  {
    version: '5.23.0',
    date: '2026-08-10',
    sections: [
      {
        heading: 'Added',
        entries: [
          'Accept option groups on the multi-select, dropdown, and autocomplete, each rendering under its own heading or under a rule when unlabelled.',
        ],
      },
    ],
  },
  {
    version: '5.22.1',
    date: '2026-08-08',
    sections: [
      {
        heading: 'Fixed',
        entries: [
          "Pin the dialog's and drawer's close button back to the top-right corner of the panel.",
        ],
      },
    ],
  },
  {
    version: '5.22.0',
    date: '2026-08-08',
    sections: [
      {
        heading: 'Added',
        entries: [
          "Cap a tag's width with `maxWidth`, 200px by default, ellipsizing a longer label and revealing its full text in a tooltip above or below the chip.",
          "Cap the multi-select's option panel to the field's width and its chips with `maxChipWidth`, with a tooltip on any option label the panel clips.",
          "Emit the file uploader's drag-over state, and expose custom properties for the dropzone's background and text colours.",
        ],
      },
      {
        heading: 'Changed',
        entries: [
          "Open the multi-select panel from the field's edge rather than from the chip row, matching every other field.",
        ],
      },
      {
        heading: 'Fixed',
        entries: [
          "Handle `dragenter` in the file uploader, which used to leave a wrapping element's own drag state stuck on.",
          "Stop a field nested inside a bound field adopting the outer control's error, which repeated the message under every option in a multi-select.",
          'Hold the multi-select trigger at one height whether or not it holds chips.',
        ],
      },
    ],
  },
  {
    version: '5.21.0',
    date: '2026-08-08',
    sections: [
      {
        heading: 'Added',
        entries: [
          'Give the toast an optional title, shown above the message, which steps the message back when set.',
          "Accept a date typed straight into the date picker, in ISO, all-numeric, or month-name form, and rewrite it in the picker's own format.",
        ],
      },
      {
        heading: 'Changed',
        entries: [
          "**Breaking:** Drop the date picker's default placeholder text; pass `placeholder` to show one.",
          'Enlarge the toast icon and give it more room from the text beside it.',
          'Quiet a readonly field under the pointer: no focus ring on click, no hover on its icons, and no pointer cursor.',
        ],
      },
    ],
  },
  {
    version: '5.20.0',
    date: '2026-08-08',
    sections: [
      {
        heading: 'Added',
        entries: [
          'Give the number input a `maxDigits` input, capping how many characters it accepts and sizing the field to match.',
        ],
      },
      {
        heading: 'Changed',
        entries: [
          '**Breaking:** Size the number input to the characters it accepts instead of filling its container, six by default, with equal-width digits so the value no longer shifts as it is typed.',
          '**Breaking:** Strip the increment and decrement buttons from the number input, leaving a plain field that still accepts only numbers and keeps its min, max, and step bounds; stepping stays on the arrow keys. The `numberInput.increment` and `numberInput.decrement` messages are removed.',
          '**Breaking:** Grow the pointer target of every clear, close, and dismiss button to the 24px WCAG 2.2 minimum without changing how large it looks, so the dense sizes stay operable.',
          "**Breaking:** Stop the field label shrinking below 12px, and error and hint text below 11px, however small the component's size is set.",
        ],
      },
    ],
  },
  {
    version: '5.19.0',
    date: '2026-08-08',
    sections: [
      {
        heading: 'Added',
        entries: [
          'Add a `2xs` size to every sized component, one step below `xs`, for dense toolbars and compact chrome.',
          'Expand the icon set with 16 media icons covering file formats, playback, and editing: file image, file video, file audio, file PDF, images, clapperboard, waveform, subtitles, picture-in-picture, aspect ratio, transcode, record, playlist, keyframe, timecode, and trim.',
        ],
      },
      {
        heading: 'Changed',
        entries: [
          '**Breaking:** Give a button that has an icon and no label equal padding on all four sides, taken from the smaller vertical value, so it renders as a square instead of a wide pill.',
        ],
      },
    ],
  },
  {
    version: '5.18.0',
    date: '2026-08-06',
    sections: [
      {
        heading: 'Changed',
        entries: [
          'Export the `EagamiUiConfig` type, so an app can name or extend the object it passes to `provideEagamiUi()`.',
        ],
      },
      {
        heading: 'Fixed',
        entries: [
          "Apply a consumer's brand palette under a strict Content Security Policy, where the theme stylesheet was dropped and the app quietly fell back to the library's own colours.",
        ],
      },
    ],
  },
  {
    version: '5.17.2',
    date: '2026-08-06',
    sections: [
      {
        heading: 'Fixed',
        entries: [
          'Show menus, dropdowns, selects, pickers, and tooltips opened from inside a dialog or drawer, which until now were painted behind the modal and unreachable.',
          'Stop Escape closing a menu or popover and the dialog around it at the same time, so one press dismisses only the innermost overlay.',
        ],
      },
    ],
  },
  {
    version: '5.17.1',
    date: '2026-08-04',
    sections: [
      {
        heading: 'Fixed',
        entries: [
          "Hide a toast's custom icon from assistive technology, matching the alert's decorative icon treatment.",
        ],
      },
    ],
  },
  {
    version: '5.17.0',
    date: '2026-08-04',
    sections: [
      {
        heading: 'Added',
        entries: [
          "Add an icon override to the toast service, so any toast can carry any icon component in place of its variant's own, or none at all.",
        ],
      },
      {
        heading: 'Changed',
        entries: [
          'Rebalance the toast: default to the small size, match the status icon to the text size, and align its gap and width cap with the alert.',
          'Enlarge the section-heading composite style from 20px to 22px, so page subsections read a clear step above body text.',
        ],
      },
      {
        heading: 'Fixed',
        entries: [
          'Stop the divider throwing a hydration error during server-side rendering when several dividers hydrate on the same page.',
        ],
      },
    ],
  },
  {
    version: '5.16.1',
    date: '2026-08-02',
    sections: [
      {
        heading: 'Fixed',
        entries: [
          "Keep the paginator's controls reachable in a container too narrow for them, where end and centre alignment pushed them off the start edge with no way to scroll back.",
          "Stop the transfer list's panes collapsing to a width that clips their own item labels.",
          'Centre the wordmark against text placed beside it, where a line box left empty space under the logo.',
        ],
      },
    ],
  },
  {
    version: '5.16.0',
    date: '2026-08-02',
    sections: [
      {
        heading: 'Added',
        entries: [
          'Add an `orientation` input to the stepper, so steps can stack vertically where a row will not fit.',
        ],
      },
    ],
  },
  {
    version: '5.15.1',
    date: '2026-08-02',
    sections: [
      {
        heading: 'Fixed',
        entries: [
          "Re-disable the avatar editor's revert control once the crop is panned or zoomed back to where it started.",
          "Keep the avatar editor's revert control disabled while a replacement image is still loading.",
        ],
      },
    ],
  },
  {
    version: '5.15.0',
    date: '2026-08-01',
    sections: [
      {
        heading: 'Changed',
        entries: [
          'Build and test against Angular 22 and TypeScript 6. The supported peer range is unchanged, so Angular 21 and 22 consumers are both still supported.',
        ],
      },
      {
        heading: 'Fixed',
        entries: [
          "Release the avatar editor's drag listeners when it is destroyed mid-drag, which previously left them bound to the document.",
          "Re-clamp the avatar editor's image when the canvas shrinks, which could leave a gap inside the frame.",
        ],
      },
    ],
  },
  {
    version: '5.14.4',
    date: '2026-08-01',
    sections: [
      {
        heading: 'Fixed',
        entries: [
          "Expose the colour picker's saturation area as a slider carrying its own value, instead of a role that switches screen readers out of browse mode without reporting anything.",
          "Keep each date picker's keyboard focus inside its own calendar when more than one is open.",
          'Stop a popover erroring when an application dispatches a scroll event directly at the window.',
        ],
      },
    ],
  },
  {
    version: '5.14.3',
    date: '2026-08-01',
    sections: [
      {
        heading: 'Fixed',
        entries: [
          'Emit the colour in the newly chosen notation as soon as the format toggle is cycled, instead of leaving the bound value in the previous format until the next edit.',
          "Send the color picker's hue slider to the end of the strip on End, which previously jumped back to the start.",
          'Mark the matching colour preset as pressed regardless of which output format the value uses.',
          'Keep the colour swatch opaque when the alpha slider is hidden, matching the value the picker actually emits.',
        ],
      },
    ],
  },
  {
    version: '5.14.2',
    date: '2026-08-01',
    sections: [
      {
        heading: 'Fixed',
        entries: [
          'Name the menu, color picker, and multi-select panels, whose accessible names were bound through a mismatched alias and never reached the rendered surface.',
        ],
      },
    ],
  },
  {
    version: '5.14.1',
    date: '2026-08-01',
    sections: [
      {
        heading: 'Fixed',
        entries: [
          'Step the date picker a whole month on PageUp and PageDown, which previously skipped past short months entirely when the focused day had no counterpart there.',
          "Move the date picker's keyboard focus into the month the header buttons navigate to, so days stay reachable and the next arrow key no longer jumps back.",
          'Accept percentage channels in an `rgb()` color, which were previously read as raw numbers and rendered far too dark.',
          'Normalize out-of-range `hsl()` colors instead of deriving negative or overflowing channels from them.',
          "Release the previous push target when a drawer's `pushTarget` changes while it is open, which left the old element permanently indented.",
          'Correct the migration guide, which skipped the v1 to v2 and v2 to v3 upgrades entirely.',
          'Correct several changelog entries whose stated icon counts, deprecation versions, and wordmark sizing did not match what shipped.',
          'Point the Angular Material comparison link at its current domain.',
        ],
      },
    ],
  },
  {
    version: '5.14.0',
    date: '2026-08-01',
    sections: [
      {
        heading: 'Changed',
        entries: [
          "Scale every form component's label, hint, and error text with its `size`, so a large field no longer pairs a large control with small chrome. Sizes other than `md` change appearance; `md` is unchanged.",
          "Scale the progress bar's label and value with its `size`, which previously rendered identically at every size.",
          "Scale the avatar editor's dropzone, icons, and controls continuously from `canvasSize` instead of switching at two hard-coded breakpoints, so a small canvas no longer jumps between densities.",
          "Derive the drawer's panel extent from one custom property per axis, replacing the per-size width and height rules duplicated across each placement.",
        ],
      },
      {
        heading: 'Fixed',
        entries: [
          'Open the dropdown onto the first selectable option instead of highlighting a disabled first option.',
        ],
      },
    ],
  },
  {
    version: '5.13.0',
    date: '2026-08-01',
    sections: [
      {
        heading: 'Added',
        entries: [
          'Add an `aria-label` input to `<ea-input>` and `<ea-textarea>` for fields with no visible label.',
          'Add `aria-label` and `caption` inputs to `<ea-data-table>` so a table can be named, with the caption also rendering above it.',
          'Add a `removeTabbable` input to `<ea-tag>` for chips inside a composite widget that owns keyboard navigation.',
        ],
      },
      {
        heading: 'Changed',
        entries: [
          'Announce transfer list moves in a live region so the destination and count are spoken.',
          'Name paginator page buttons beyond their bare digit.',
        ],
      },
      {
        heading: 'Fixed',
        entries: [
          'Apply menu trigger and tooltip ARIA to the control a component renders, so state reaches the button inside `<ea-button>` instead of stranding on the wrapper.',
          'Take multi-select chip remove buttons out of the tab order, which nested focusable controls inside the combobox.',
          'Draw the file uploader and avatar editor accents from the semantic color tokens so they follow a retheme.',
        ],
      },
    ],
  },
  {
    version: '5.12.2',
    date: '2026-07-31',
    sections: [
      {
        heading: 'Fixed',
        entries: [
          'Ensure time picker stepper buttons respond to keyboard activation.',
          'Announce error and warning toasts immediately, and pause toast auto-dismiss while the pointer or keyboard focus is on the stack.',
          "Make the multi-select's Select all row keyboard-accessible inside the option list, announce empty search results, and let the whole box toggle the list on click.",
          'Keep the keyboard-focused option scrolled into view in dropdown and multi-select lists.',
          "Correct the autocomplete's expanded state and selected-option announcements.",
          "Restore button semantics for the date picker's calendar day cells.",
          'Prevent a required file uploader from silently blocking form submission.',
          'Stop dialogs and drawers referencing an empty header as their accessible name.',
          'Expose disabled command palette items to assistive technology and skip them during arrow-key navigation.',
          'Let keyboard users scroll the virtual list even without an aria-label.',
          "Remove the avatar editor's invisible tab stop on its hidden file input.",
          'Mirror stepper and tree arrow-key navigation in right-to-left layouts.',
          "Add hover feedback to the tree's expand chevron, and an explicit label association to the switch.",
        ],
      },
    ],
  },
  {
    version: '5.12.1',
    date: '2026-07-29',
    sections: [
      {
        heading: 'Added',
        entries: [
          "Add a `--ea-divider-length` styling hook that pins the vertical divider's exact length.",
        ],
      },
      {
        heading: 'Changed',
        entries: ['Update development tooling dependencies.'],
      },
    ],
  },
  {
    version: '5.12.0',
    date: '2026-07-28',
    sections: [
      {
        heading: 'Added',
        entries: [
          'Add a `linked` input to the wordmark so it can render without its built-in eagami.com link, for embedding in a custom link.',
        ],
      },
      {
        heading: 'Changed',
        entries: [
          "**Breaking:** Make the wordmark `size` input the brand text's font-size in px (previously it was the logo's size); the default drops from 48 to 24 so the brand text renders at its previous size.",
          'Re-proportion the wordmark: the logo renders at 1.5 times the text size, with a gap of one twelfth of the logo between them.',
          'Change the wordmark byline to "designed by" in every locale.',
          "Tuck the wordmark byline closer to the brand text, and raise the tagline variant's text for optical balance against the logo.",
        ],
      },
    ],
  },
  {
    version: '5.11.0',
    date: '2026-07-25',
    sections: [
      {
        heading: 'Added',
        entries: [
          'Add a `--ea-dialog-size` custom property that drives the dialog panel width.',
        ],
      },
      {
        heading: 'Changed',
        entries: [
          "**Breaking:** Make the tree expand chevron decorative; expansion state is announced via the treeitem's `aria-expanded` and toggled with the arrow keys. The tree-node `expandLabel` and `collapseLabel` inputs and the `tree.expand`/`tree.collapse` locale messages are removed.",
        ],
      },
    ],
  },
  {
    version: '5.10.1',
    date: '2026-07-24',
    sections: [
      {
        heading: 'Added',
        entries: [
          'Add checkbox label and count colour styling hooks (`--ea-checkbox-label-color`, `--ea-checkbox-count-color`).',
        ],
      },
      {
        heading: 'Fixed',
        entries: [
          'Mark the Framer icon as a brand icon, matching the other brand marks.',
        ],
      },
    ],
  },
  {
    version: '5.10.0',
    date: '2026-07-24',
    sections: [
      {
        heading: 'Added',
        entries: [
          'Allow the tooltip to render a TemplateRef, so consumers can show styled multi-part content instead of a plain string.',
        ],
      },
      {
        heading: 'Changed',
        entries: [
          '**Breaking:** Remove the share-2 icon, which was an accidental duplicate of the share icon.',
        ],
      },
      {
        heading: 'Fixed',
        entries: [
          'Let the tooltip bubble grow past its max width instead of clipping unbreakable template content such as avatars and icon rows.',
        ],
      },
    ],
  },
  {
    version: '5.9.0',
    date: '2026-07-24',
    sections: [
      {
        heading: 'Added',
        entries: [
          'Add 10 commonly used icons: bug, building, calculator, history, lightbulb, megaphone, palette, pin, plug, and timer.',
        ],
      },
    ],
  },
  {
    version: '5.8.6',
    date: '2026-07-21',
    sections: [
      {
        heading: 'Changed',
        entries: [
          'Update the README to list all components (adding Form Field, Number Input, and Timeline) and reflect the Angular v21 and v22 peer range.',
        ],
      },
      {
        heading: 'Fixed',
        entries: [
          'Mark the Twitter, Instagram, Trello, and Dribbble icons as brand icons (`isBrand`), matching the other Feather brand marks.',
        ],
      },
    ],
  },
  {
    version: '5.8.5',
    date: '2026-07-18',
    sections: [
      {
        heading: 'Fixed',
        entries: [
          "Give the command palette's search input a visible focus ring for keyboard users.",
          "Make the paginator's page-size dropdown chevron follow the theme colour so it is visible in dark mode, and scale it with the paginator's size.",
        ],
      },
    ],
  },
  {
    version: '5.8.4',
    date: '2026-07-18',
    sections: [
      {
        heading: 'Changed',
        entries: [
          'Align the avatar editor controls and number input steppers with the shared icon-button styling so their hover, focus, and disabled states match the rest of the library.',
        ],
      },
    ],
  },
  {
    version: '5.8.3',
    date: '2026-07-18',
    sections: [
      {
        heading: 'Fixed',
        entries: [
          "Scale the color picker's popover with its size input, so the saturation area, hue and alpha sliders, value inputs, and preset swatches grow with the field instead of staying a fixed size.",
        ],
      },
    ],
  },
  {
    version: '5.8.2',
    date: '2026-07-18',
    sections: [
      {
        heading: 'Fixed',
        entries: [
          "Scale the time picker's popover with its size input, so the hour/minute steppers, value fields, and AM/PM controls grow with the field instead of staying fixed.",
          'Make the switch, badge dot, slider and range-slider min/max labels, and the dropdown, autocomplete, and multi-select option rows scale proportionally with their size input; the badge dot now covers the full size range without an abrupt jump.',
        ],
      },
    ],
  },
  {
    version: '5.8.1',
    date: '2026-07-17',
    sections: [
      {
        heading: 'Fixed',
        entries: [
          'Make the transfer list and tree scale proportionally across all sizes: list heights, row padding, indentation, and the transfer controls now grow smoothly with the size input instead of jumping between a few hand-set steps, so adjacent sizes are no longer identical.',
        ],
      },
    ],
  },
  {
    version: '5.8.0',
    date: '2026-07-16',
    sections: [
      {
        heading: 'Added',
        entries: [
          'Add a size input to the menu, accordion, breadcrumbs, data table, form field, and toast components, scaling all inner text, paddings, and icons proportionally from the shared font-size scale; menu items and accordion items inherit the size from their parent.',
        ],
      },
      {
        heading: 'Changed',
        entries: [
          '**Breaking:** the menu, accordion, breadcrumbs, data table, and toast components now default to the shared md font scale (16px) instead of their previous fixed 14px text, so they render slightly larger out of the box; pass `size="sm"` to keep the old appearance.',
        ],
      },
    ],
  },
  {
    version: '5.7.0',
    date: '2026-07-14',
    sections: [
      {
        heading: 'Added',
        entries: [
          "Support lazy locale loading: register `localeLoaders` in `provideEagamiUi()` to fetch a language's dictionary on demand the first time it is activated, preload one with `EagamiI18nService.loadLocale()`, and fall back to English if a load fails.",
        ],
      },
    ],
  },
  {
    version: '5.6.2',
    date: '2026-07-13',
    sections: [
      {
        heading: 'Changed',
        entries: [
          "Publish the React and Flutter integration guides and a machine-readable design-token export (JSON) on eagami.com, kept in sync with the library's design tokens on every release.",
        ],
      },
      {
        heading: 'Fixed',
        entries: [
          'Sync stale values in the integration guides: dark-mode shadows, font stacks, secondary brand washes, and missing newer tokens.',
        ],
      },
    ],
  },
  {
    version: '5.6.1',
    date: '2026-07-12',
    sections: [
      {
        heading: 'Changed',
        entries: [
          'Drop the redundant publish flag; npm provenance is still generated automatically by trusted publishing.',
          'Sync the React and Flutter integration guides to the current token set (refreshed secondary palette).',
        ],
      },
    ],
  },
  {
    version: '5.6.0',
    date: '2026-07-11',
    sections: [
      {
        heading: 'Added',
        entries: [
          'Add 21 icons: 11 general-purpose (folder-open, file-check, shield-check, bell-ring, clipboard-list, mail-check, calendar-days, git-compare, bookmark-plus, languages, keyboard) and 10 brand marks (Svelte, Node.js, Vue.js, Angular, Python, WordPress, Shopify, Android, Pinterest, Bluesky).',
        ],
      },
    ],
  },
  {
    version: '5.5.0',
    date: '2026-07-10',
    sections: [
      {
        heading: 'Added',
        entries: [
          'Add a timeline: a vertical or horizontal sequence of events, each a colored node on a connecting line with an optional heading, timestamp, and description. A single item can be flagged as current to highlight it in the secondary brand color, and an alternate layout zig-zags content to either side of a centered line.',
        ],
      },
    ],
  },
  {
    version: '5.4.0',
    date: '2026-07-10',
    sections: [
      {
        heading: 'Added',
        entries: [
          'Add a number input: a numeric field with increment and decrement steppers, min/max/step bounds, and the standard label, hint, and error chrome, integrated with Angular forms.',
        ],
      },
    ],
  },
  {
    version: '5.3.0',
    date: '2026-07-08',
    sections: [
      {
        heading: 'Added',
        entries: [
          'Add a `buffer` input to the progress bar that renders the buffered-ahead segment in the secondary brand color, for download-then-process style progress.',
          'Add a `clearable` input to the color picker (default `true`) to show or hide the clear button, matching the other form inputs.',
        ],
      },
      {
        heading: 'Changed',
        entries: [
          'Put the secondary brand color to work as a native accent: the date picker marks today in it (the selected day stays primary) and the stepper marks the current step in it (completed steps stay primary). Secondary brand tokens now carry full light and dark coverage.',
          'Refresh the default secondary brand color to a cooler blue-violet.',
        ],
      },
    ],
  },
  {
    version: '5.2.2',
    date: '2026-07-07',
    sections: [
      {
        heading: 'Added',
        entries: [
          'Add a runnable starter example that opens in StackBlitz, linked from the README for a no-install first look.',
        ],
      },
    ],
  },
  {
    version: '5.2.1',
    date: '2026-07-04',
    sections: [
      {
        heading: 'Changed',
        entries: [
          'Expand the README with a comparison to other Angular UI libraries and a stability and support overview.',
        ],
      },
    ],
  },
  {
    version: '5.2.0',
    date: '2026-07-04',
    sections: [
      {
        heading: 'Added',
        entries: [
          "Add a form field component that wraps native inputs, selects, and textareas in the library's standard field chrome: label with required marker, hint, and error messages, with localized validation errors auto-derived from a bound form control and automatic label and aria wiring.",
        ],
      },
    ],
  },
  {
    version: '5.1.0',
    date: '2026-07-03',
    sections: [
      {
        heading: 'Added',
        entries: [
          "Add a `headingLevel` input to the accordion so item headers join the page's heading outline, and `ariaLabel` inputs to the autocomplete, multi-select, tabs, and virtual list for naming controls that render no visible label.",
          'Give the popover opt-in focus containment via `trapFocus` and `aria-labelledby` forwarding, for dialog-style surfaces.',
          "Document the library's WCAG 2.2 AA conformance and accessibility guarantees in the README.",
        ],
      },
      {
        heading: 'Fixed',
        entries: [
          'Announce the date and time picker popovers as named, focus-contained dialogs, move screen-reader focus along with arrow-key navigation in the calendar, and keep out-of-range days perceivable instead of removing them from the accessibility tree.',
          'Expose the dropdown trigger as a combobox so the highlighted option is announced while arrowing, include the selected value in its accessible name, and support Home, End, and type-ahead.',
          'Follow the ARIA listbox pattern in the multi-select and transfer list: valid option semantics, active-option announcement, and roving keyboard focus with arrow, Home, and End keys.',
          'Turn sortable data-table headers into real buttons so screen readers know they are operable, and announce the empty state.',
          'Announce toasts, alerts, file-uploader activity, and avatar-editor errors reliably by keeping live regions mounted before their content arrives and removing duplicate nested regions.',
          'Dismiss hover-triggered tooltips with Escape regardless of where keyboard focus is.',
          "Name previously unnamed controls: range-slider thumbs, the stepper and tabs tablists, decorative avatars, file-upload progress bars, the color-picker trigger and presets, and the paginator's page-size select (now with per-instance ids).",
          'Make every interaction keyboard-reachable: the input clear button, changing the avatar-editor photo, scrolling the virtual list, and closing the time picker with Escape from any control inside it; menus now use roving tabindex so Tab leaves the menu.',
          'Expose states that were visual-only to assistive technology: AM/PM selection, completed steps, rating required and error states, avatar-editor loading, live color-picker saturation and brightness announcements, and page-range updates in the paginator.',
          'Skip disabled options when the segmented control decides its keyboard tab stop.',
          'Localize all new screen-reader strings in every supported language.',
        ],
      },
    ],
  },
  {
    version: '5.0.1',
    date: '2026-07-02',
    sections: [
      {
        heading: 'Fixed',
        entries: [
          'Fix bottom and right drawers snapping open or overshooting and sliding faster than the selected animation, instead of easing in smoothly like left and top drawers.',
          "Align the switch label's font size with other basic form controls like radio and checkbox across all size variants.",
        ],
      },
    ],
  },
  {
    version: '5.0.0',
    date: '2026-07-02',
    sections: [
      {
        heading: 'Added',
        entries: [
          'Add a `push` mode to the drawer that opens it non-modally and reflows the page content aside instead of overlaying it, always keeping a strip of content visible, plus a `pushTarget` input to choose which element gets pushed. `closeOnBackdrop` now dismisses the drawer on an outside click in both overlay and push modes.',
        ],
      },
      {
        heading: 'Changed',
        entries: [
          "**Breaking:** Replace the drawer's boolean `animated` input with an `animation` input accepting `none`, `linear`, or `eased` (default `eased`); the panel now slides both in on open and out on close.",
          "**Breaking:** Rename the drawer's `width` input to `size`, which sets the panel's extent along its main axis (width for side drawers, height for top and bottom).",
        ],
      },
      {
        heading: 'Fixed',
        entries: [
          "Keep the date picker's weekday and month names, and grouped numbers in the slider, range-slider, and paginator, in the active locale even on browsers whose built-in `Intl` omits that locale's data, instead of silently falling back to English.",
          'Translate the avatar-editor file-validation errors and tree expand/collapse labels in every locale.',
          "Scale the date picker's calendar popover with the `size` input (its text, day cells, and controls), not only the trigger.",
        ],
      },
    ],
  },
];
